In [20]:
#라이브러리 불러오기
import pandas as pd
import tensorflow as tf


In [21]:
#학습할 데이터 준비
path = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
iris = pd.read_csv(path)
iris.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭      품종
0   5.1  3.5    1.4   0.2  setosa
1   4.9  3.0    1.4   0.2  setosa
2   4.7  3.2    1.3   0.2  setosa
3   4.6  3.1    1.5   0.2  setosa
4   5.0  3.6    1.4   0.2  setosa

In [22]:
#원핫인코딩
iris = pd.get_dummies(iris)
iris.columns

Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종_setosa', '품종_versicolor',
       '품종_virginica'],
      dtype='object')

In [24]:
#독립변수, 종속변수 
ind = iris[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
dep = iris[['품종_setosa', '품종_versicolor', '품종_virginica']]
print(ind.shape, dep.shape)

(150, 4) (150, 3)


In [29]:
"""
분류 예측:
    Sigmoid
    Softmaxb 비율로 예측하기 위해  
        차이점 숙제
        -> 사용
"""
#2.모델의 구조를 만듭니다.

X = tf.keras.layers.Input(shape=[4])
Y = tf.keras.layers.Dense(3, activation='softmax')(X)
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy',
              metrics='accuracy')

In [49]:
# 3.데이터로 모델을 학습(FIT)합니다.
# model.fit(ind, dep, epochs=10000, verbose=0)
model.fit(ind, dep, epochs=10)

Epoch 1/100
5/5 [==============================] - 0s 2ms/step - loss: 0.0476 - accuracy: 0.9800
Epoch 2/100
5/5 [==============================] - 0s 1ms/step - loss: 0.0473 - accuracy: 0.9800
Epoch 3/100
5/5 [==============================] - 0s 2ms/step - loss: 0.0471 - accuracy: 0.9800
Epoch 4/100
5/5 [==============================] - 0s 1ms/step - loss: 0.0469 - accuracy: 0.9800
Epoch 5/100
5/5 [==============================] - 0s 1ms/step - loss: 0.0471 - accuracy: 0.9800
Epoch 6/100
5/5 [==============================] - 0s 997us/step - loss: 0.0472 - accuracy: 0.9800
Epoch 7/100
5/5 [==============================] - 0s 1ms/step - loss: 0.0470 - accuracy: 0.9800
Epoch 8/100
5/5 [==============================] - 0s 2ms/step - loss: 0.0473 - accuracy: 0.9800
Epoch 9/100
5/5 [==============================] - 0s 1ms/step - loss: 0.0472 - accuracy: 0.9800
Epoch 10/100
5/5 [==============================] - 0s 1ms/step - loss: 0.0470 - accuracy: 0.9800
Epoch 11/100
5/5 [=========

In [55]:
# 4. 모델을 이용합니다
# 맨 처음 데이터 5개

print(model.predict(ind[-5:]))
print(dep[-5:])

[[1.9744200e-25 1.4893911e-03 9.9851054e-01]
 [1.2675511e-23 1.1231993e-02 9.8876804e-01]
 [7.3712570e-23 2.0564791e-02 9.7943521e-01]
 [3.7688184e-26 6.4424350e-04 9.9935573e-01]
 [1.3198513e-21 5.3317487e-02 9.4668257e-01]]
     품종_setosa  품종_versicolor  품종_virginica
145          0              0             1
146          0              0             1
147          0              0             1
148          0              0             1
149          0              0             1


In [56]:
# 학습한 가중치
model.get_weights()

[array([[  4.811459 ,   1.3725691,  -1.5846368],
        [ 10.472301 ,   1.5235671,  -3.094339 ],
        [-15.722176 ,  -2.3316615,   3.7055898],
        [-18.762222 ,  -5.478724 ,   5.3077474]], dtype=float32),
 array([ 7.4657645,  7.544773 , -8.482923 ], dtype=float32)]