In [2]:
#라이브러리 불러오기
import pandas as pd
import tensorflow as tf


In [4]:
#학습할 데이터 준비
path = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
iris = pd.read_csv(path)
iris.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭      품종
0   5.1  3.5    1.4   0.2  setosa
1   4.9  3.0    1.4   0.2  setosa
2   4.7  3.2    1.3   0.2  setosa
3   4.6  3.1    1.5   0.2  setosa
4   5.0  3.6    1.4   0.2  setosa

In [6]:
#원핫인코딩
iris = pd.get_dummies(iris)
iris.columns


Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종_setosa', '품종_versicolor',
       '품종_virginica'],
      dtype='object')

In [8]:
#독립변수, 종속변수 
ind = iris[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
dep = iris[['품종_setosa', '품종_versicolor', '품종_virginica']]
print(ind.shape, dep.shape)

(150, 4) (150, 3)


In [15]:
#2.모델의 구조를 만듭니다.

X = tf.keras.layers.Input(shape=[4])
H = tf.keras.layers.Dense(8, activation='swish')(X)
H = tf.keras.layers.Dense(8, activation='swish')(H)
H = tf.keras.layers.Dense(8, activation='swish')(H)
Y = tf.keras.layers.Dense(3, activation='softmax')(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy',
              metrics='accuracy')

In [18]:
# 3.데이터로 모델을 학습(FIT)합니다.
model.fit(ind, dep, epochs=1000, verbose=0)
model.fit(ind, dep, epochs=10)

Epoch 1/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0438 - accuracy: 0.9867
Epoch 2/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0473 - accuracy: 0.9800
Epoch 3/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0454 - accuracy: 0.9667
Epoch 4/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0463 - accuracy: 0.9800
Epoch 5/10
5/5 [==============================] - 0s 1ms/step - loss: 0.0491 - accuracy: 0.9800
Epoch 6/10
5/5 [==============================] - 0s 1ms/step - loss: 0.0437 - accuracy: 0.9733
Epoch 7/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0406 - accuracy: 0.9800
Epoch 8/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0513 - accuracy: 0.9733
Epoch 9/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0546 - accuracy: 0.9733
Epoch 10/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0461 - accuracy: 0.9800


In [19]:
# 4. 모델을 이용합니다
# 맨 처음 데이터 5개
print(model.predict(ind[0:5]))
print(dep[0:5])

[[1.00000000e+00 1.28858355e-08 7.35034922e-10]
 [1.00000000e+00 1.12818803e-08 7.38515804e-10]
 [1.00000000e+00 7.72648523e-09 4.20849799e-10]
 [1.00000000e+00 7.87943222e-09 4.36938985e-10]
 [1.00000000e+00 1.53210866e-08 8.62702965e-10]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0
